export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAILED = 'GET_WEATHER_FAILED';

export const GET_WEATHER_LOADING = 'GET_WEATHER_LOADING';

export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS';
export const GET_CURRENT_WEATHER_FAILED = 'GET_CURRENT_WEATHER_FAILED';
export const GET_CURRENT_WEATHER_LOADING = 'GET_CURRENT_WEATHER_LOADING';

export const UPDATE_WEATHER_DATA = 'UPDATE_WEATHER_DATA';

export const SEARCH_DATA = 'SEARCH_DATA';
export const CLEAR_SEARCH_DATA = 'CLEAR_SEARCH_DATA';
